version: 2

sources:
  - name: postgres
    schema: dw
    tables: 
      - name: bronze-criptosinfo
        description: "Tabela bruta com as informações quantitativas das criptomoedas"
        columns:
          - name: "cripto"
            description: "simbolo da cripto"
          - name: "price"
            description: "preço"
          - name: "high"
            description: "high"
          - name: "low"
            description: "low"
          - name: "bid"
            description: "bid"
          - name: "ask"
            description: "ask"
          - name: "volume"
            description: "volume"
          - name: "quote_volume"
            description: "quote_volume"
          - name: "order_book_bid"
            description: "order_book_bid"
          - name: "order_book_ask"
            description: "order_book_ask"
          - name: "data_extracao"
            description: "data da extração"

      - name: bronze-criptosnews
        description: "Tabela com dados brutos das noticias sobre criptomoedas"
        columns:
          - name: titulo
            description: "titulo da noticia"
          - name: url
            description: "url da noticia"
          - name: moedas
            description: "moedas que foram ditas na noticia"
          - name: publicado_em
            description: "data da publicação"
          - name: fonte
            description: "fonte da noticia"

      - name: silver-criptosinfo
        description: "Tabela com calculos estrategicos"
        columns:
          - name: "cripto"
            description: "simbolo da cripto"
          - name: "price"
            description: "preço"
          - name: "high"
            description: "high"
          - name: "low"
            description: "low"
          - name: "bid"
            description: "bid"
          - name: "ask"
            description: "ask"
          - name: "volume"
            description: "volume"
          - name: "quote_volume"
            description: "quote_volume"
          - name: "order_book_bid"
            description: "order_book_bid"
          - name: "order_book_ask"
            description: "order_book_ask"
          - name: "data_extracao"
            description: "data da extração"
          - name: "tedencia_preco"
            description: "tedencia_preco"
          - name: "rsi_14"
            description: "rsi_14"
          - name: "macd"
            description: "macd"
          - name: "ma_7"
            description: "ma_7"
          - name: "spread"
            description: "spread"
          - name: "ordem_livro_sinal"
            description: "ordem_livro_sinal"
          - name: "dominancia_btc"
            description: "dominancia_btc"

      - name: gold-criptosinfo
        description: "Tabela com as informações comprar, vender ou esperar"
        columns:
          - name: "cripto"
            description: "simbolo da cripto"
          - name: "price"
            description: "preço"
          - name: "high"
            description: "high"
          - name: "low"
            description: "low"
          - name: "bid"
            description: "bid"
          - name: "ask"
            description: "ask"
          - name: "volume"
            description: "volume"
          - name: "quote_volume"
            description: "quote_volume"
          - name: "order_book_bid"
            description: "order_book_bid"
          - name: "order_book_ask"
            description: "order_book_ask"
          - name: "data_extracao"
            description: "data da extração"
          - name: "recomendacao"
            description: "recomendacao para comprar/vender/esperar"